# Generated by Django 4.1.1 on 2022-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=40)),
                ('product_desc', models.CharField(default='', max_length=1000)),
                ('product_image', models.ImageField(default='', upload_to='Images')),
                ('product_price', models.IntegerField(default=0)),
                ('product_brand', models.CharField(default='', max_length=40)),
                ('product_condition', models.CharField(default='', max_length=4)),
                ('product_reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
