# Generated by Django 4.1.1 on 2022-10-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('message_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('message_sender', models.CharField(default='', max_length=20)),
                ('message_email', models.EmailField(default='', max_length=30)),
                ('message_content', models.CharField(default='', max_length=2000)),
            ],
        ),
    ]
