# Generated by Django 4.1.1 on 2022-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_name', models.CharField(default='', max_length=40)),
                ('order_email', models.CharField(default='', max_length=40)),
                ('order_address', models.CharField(default='', max_length=200)),
                ('order_country', models.CharField(default='', max_length=12)),
                ('order_city', models.CharField(default='', max_length=12)),
                ('order_zipcode', models.IntegerField(default=0)),
                ('order_phone_number', models.IntegerField(default=0)),
                ('order_json', models.CharField(default='', max_length=3000)),
            ],
        ),
    ]
